<?php
defined('WEKIT_VERSION') or exit(403);
Wind::import('APPS:admin.library.AdminBaseController');
/**
 * 后台访问入口
 *
 * generated by phpwind.com
 */
class ManageController extends AdminBaseController {


	
	public function run() {
		$service = $this->_loadConfigService();
		$config = $service->getValues('geetest');
		$config['model'] = json_decode($config['model'],true);
		if (empty($config['model'])) {
			$config['model'] = array("register","login","run","reply","modify");	
		}		
		if (empty($config['publickey']) || empty($config['privatekey'])) {
			$config['publickey'] = "a40fd3b0d712165c5d13e6f747e948d4";
			$config['privatekey'] = "0f1a37e33c9ed10dd2e133fe2ae9c459";
		}
		$this->setOutput($config, 'config');
	}
	public function aboutAction(){
		$service = Wekit::load ( 'config.PwConfig' );
		$config = $service->getValues ( 'geetest' );
		$this->setOutput ( $config, 'config' );
	}
	public function dorunAction(){
		$publickey = $this->getInput('publickey','post',true);
		$privatekey = $this->getInput('privatekey','post',true);
		$model = $this->getInput('model','post',true);
		$model = json_encode($model);
		$open = $this->getInput('open','post',true);
		$update = array(
				'publickey' =>$publickey,
				'privatekey' => $privatekey,
				'model' => $model,
				'open' => $open
			);
		$this->_setConfig($update);
		$this->showMessage ( '设置成功');	
	}

	private function _setConfig($update)
    {
        $config = new PwConfigSet ( 'geetest' );
		foreach ( $update as $k => $v ) {
			$config->set ( $k, $v )->flush ();
		}
    }
	private function _loadConfigService(){
		return Wekit::load('config.PwConfig');
	}
}

?>